college_name=input("Enter Name Of your College: ")
Student_name=input("Enter Name of Student: ")
Roll_no=input("Enter student's Roll no.: ")
Registration_no=input("Enter your Registration no.: ")
Course=input("Enter course name(BCA,BBA,MBA): ")
Email=input("Enter e-mail address: ")
print("\n**** COLLEGE INFORMATION ****\n")
print("College Name:",college_name)
print("Student Name:",Student_name)
print("Roll no.:",Roll_no)
print("Registration No.:",Registration_no)
print("Course Name:",Course)
print("E-mail address:",Email)
