# import pandas as pd
# df=pd.read_csv("emp data.csv")
# print(df)
# print()
# print(df.head())
# print()
# print("Information")
# print(df.info())
# print()
# print("Filling Missing values in Experience Column")
# print(df["Experience"].fillna(df["Experience"].mean()))
# print()
# print("Filling Missing values in Salary Column")
# print(df["Salary"].fillna(df["Salary"].mean()))
# print()
# print("Filling Missing values in Performace Column")
# print(df["Performace Rating"].fillna(df["Performace Rating"].mean()))
# print()
# print("Duplicate Rows")
# print(df.duplicated())
# print()
# print("Remove Duplicate Rows")
# print(df.drop_duplicates())
# print()
# print("Department with Highest average Salary")
# print(df.groupby("Department")["Salary"].max())
# print()
# print("City With Higest Average Performace Rating")
# print(df.groupby("City")["Performace Rating"].mean().sort_values(ascending=False).head(1))
# print()
# print("Top 5 Highest Paid Employess")
# print(df.sort_values("Salary",ascending=False).head(5))
# print()


# import matplotlib.pyplot as plt
# category_salary=df.groupby("Department")["Salary"].mean()
# category_salary.plot(kind="bar")
# plt.title("Average Salary")
# plt.xlabel("x axis")
# plt.ylabel("y axis")
# plt.show()

# city=df["City"].value_counts()
# city.plot(kind="pie",autopct="%1.1f%%")
# plt.title("City Pie Chart")
# plt.show()

# plt.hist(df["Salary"],bins=5)
# plt.title("Salary Histogram")
# plt.xlabel("Value")
# plt.ylabel("Frequency")
# plt.show()

# print("Five Business Insights")
# print()
# print("Which department pays the highest average salary?")
# print("Which city has the most employees?")
# print("Which employee earns the highest salary?")
# print("How many employees work in each department?")
# print("What is the average salary in Delhi?.")

# Exercise-2
# import pandas as pd
# df=pd.read_csv("sales record.csv")
# print(df)
# print()
# df["Total"]=df["Price"]*df["Quantity"]-df["Discount"]
# print(df)
# print()
# print("higest Revenue product")
# print(df.groupby("Product")["Total"].max().head(1))
# print("lowest Revenue Product")
# print(df.groupby("Product")["Total"].min().head(1))
# print()
# print("city with Higest Order Sales")
# print(df.groupby("City")["Total"].max().head(1))
# print()
# print("Average Order Value By category")
# print(df.groupby("Category")["Quantity"].mean())
# print()

# import matplotlib.pyplot as plt
# plt.bar(df["Category"],df["Total"],color="red")
# plt.xlabel("Category")
# plt.ylabel("Revenue")
# plt.title("Category wisw revenue")
# plt.show()

# plt.hist(df["Price"])
# plt.title("Sales ditribution")
# plt.xlabel("Price")
# plt.ylabel("Frequency")
# plt.show()

# order=df["City"].value_counts()
# order.plot(kind="pie",autopct="%1.1f%%")
# plt.title("Pie Chart")
# plt.show()

# print("Business Recommendations")
# print("1. Increase the stock of best-selling products.")
# print("2. Give discounts on low-selling products.")
# print("3. Focus more on cities with high sales.")
# print("4. Advertise products that sell less.")
# print("5. Offer special deals to attract more customers.")


# exercise-3
# import pandas as pd
# df=pd.read_csv("patient record.csv")
# print(df)
# print("indentify duplicate patients")
# print(df.duplicated())
# print()
# print("Department that generating highest Revenue")
# print(df.groupby("Department")["Bill Amount"])
# print()
# print("Maximum number of patient treating by the doctor")
# doctor = df["Doctor"].value_counts()
# print(doctor.head(1))
# print()
# print(" City Contributing the Highest revenue")
# city_revenue=df.groupby("City")["Bill Amount"].sum().sort_values(ascending=False)
# print(city_revenue.head(1))
# print()

# import matplotlib.pyplot as plt

# plt.hist(df["Bill Amount"])
# plt.title("Histogram")
# plt.xlabel("value")
# plt.ylabel("Frequency")
# plt.show()

# order=df["Department"].value_counts()
# order.plot(kind="pie",autopct="%1.1f%%")
# plt.title("Pie Chart")
# plt.show()

# print(" Five Observations on hospital management")
# print("1.The department generating the highest revenue should be given more resources and staff support.")
# print("2.Doctors treating more patients may require better scheduling and workload management.")
# print("3.Cities with higher patient visits can be targeted for better healthcare services.")
# print("4.Departments with fewer patients should be promoted to increase awareness and improve services.")
# print("5.Patient records should be regularly updated to maintain accurate data and improve decision-making")


# exercise-4
# import pandas as pd
# df=pd.read_csv("movie record.csv")
# print(df)
# print()
# print("Remove Duplicate Titles")
# print(df[df.duplicated("Title")])
# print()
# print("Fill missing Rating with the average rating")
# print(df["Rating"].fillna(df["Rating"].mean()))
# print()
# print("Most Popular Genre")
# print(df["Genre"].value_counts().head(1))
# print()
# print("Average duration of genre")
# print(df.groupby("Genre")["Duration"].mean())
# print()
# print("Highest rated movie")
# print(df.groupby("Title")["Rating"].max().head(1))
# print()
# print("Number of Movies Released after 2020")
# print(df[df["Release Year"]>2020])
# print()

# import matplotlib.pyplot as plt

# plt.hist(df["Duration"])
# plt.title("Histogram")
# plt.xlabel("value")
# plt.ylabel("Frequency")
# plt.show()

# order=df["Language"].value_counts()
# order.plot(kind="pie",autopct="%1.1f%%")
# plt.title("Pie Chart")
# plt.show()


# print("Five Insights for Streaming Platform")
# print()
# print("1. Popular genres should get more content investment.")
# print("2. Highly rated movies can be promoted more on the platform.")
# print("3. User preferences can be studied based on language distribution.")
# print("4. New releases after 2020 can attract more viewers.")
# print("5. Short and long duration content should be balanced for different audiences.")


# Exercise-5

# import pandas as pd
# df=pd.read_csv("e-commerce.csv")
# print(df)
# print()
# print("Highest Price")
# print(df.groupby("Product_Category")["Unit_Price"].max().head(5))
# print()
# print("Lowest Price ")
# print(df.groupby("Product_Category")["Unit_Price"].min().tail(5))
# print()
# print("information About The Data")
# print(df.info())
# print()
# print("using Describe function")
# print(df.describe())
# print()
# print("Handle missing values")
# print(df["Quantity"].fillna(df["Quantity"].mean()))
# print()
# print("Show Duplicates")
# print(df.duplicated())
# print()
# print("Number of Duplicatess rows")
# print(df.duplicated().sum())
# print()
# print("Remove Duplicates")
# print(df.drop_duplicates())
# print()
# print("sorting of Product_category")
# print(df["Product_Category"].sort_values(ascending=False))
# print()
# print(df["Order Status"].sort_values(ascending=False))
# print()



# BANKING
# import pandas as pd
# import matplotlib.pyplot as plt
# df=pd.read_csv("Banking.csv")
# print(df)
# print()
# print("usinh Head")
# print(df.groupby("Customer_ID")["Balance"].max().head(5))
# print()
# print("Using tail ")
# print(df.groupby("Customer_ID")["Balance"].min().tail(5))
# print()
# print("Using Info")
# print(df.info())
# print()
# print("using Describe")
# print(df.describe())
# print()
# print("Handle missing values")
# print(df["Balance"].fillna(df["Balance"].mean()))
# print(df["Loan_Amount"].fillna(df["Loan_Amount"].mean()))
# print()
# print("Show Duplicates")
# print(df.duplicated())
# print()
# print("Number of Duplicatess rows")
# print(df.duplicated().sum())
# print()
# print("Remove Duplicates")
# print(df.drop_duplicates())
# print()
# print("1.using value_counts")
# print(df["Account_Type"].value_counts())
# print()
# print("2.using value_counts")
# print(df["Gender"].value_counts())
# print()
# print("2.using sort valuess")
# print(df["Loan_Amount"].sort_values(ascending=False))
# print()
# print("2.using sort valuess")
# print(df["Balance"].sort_values(ascending=False))
# print()
# print("1.Performing Group by analysis")
# print(df.groupby("Gender")["Loan_Amount"].max())
# print()
# print("2.Performing Group by analysis")
# print(df.groupby("Gender")["Loan_Amount"].min())
# print()
# print("3.Performing Group by analysis")
# print(df.groupby("Gender")["Loan_Amount"].mean())
# print()

# plt.hist(df["Loan_Amount"],bins=5)
# plt.title("Histogram")
# plt.xlabel("value")
# plt.ylabel("Frequency")
# plt.show()

# order=df["Branch"].value_counts()
# order.plot(kind="pie",autopct="%1.1f%%")
# plt.title("Pie Chart")
# plt.show()

# import matplotlib.pyplot as plt
# plt.bar(df["Gender"],df["Loan_Amount"],color="red")
# plt.xlabel("X axis")
# plt.ylabel("Y axis")
# plt.title("Bar graph")
# plt.show()


# Education

# import pandas as pd
# import matplotlib.pyplot as plt
# df=pd.read_csv("Education.csv")
# print(df)
# print()
# print("usinh Head")
# print(df.groupby("Department")["Attendance (%)"].max().head(5))
# print()
# print("Using tail ")
# print(df.groupby("Department")["Attendance (%)"].min().tail(5))
# print()
# print("Using Info")
# print(df.info())
# print()
# print("using Describe")
# print(df.describe())
# print()
# print("Handle missing values")
# print(df["Marks"].fillna(df["Marks"].mean()))
# print(df["Attendance (%)"].fillna(df["Attendance (%)"].mean()))
# print()
# print("Show Duplicates")
# print(df.duplicated())
# print()
# print("Number of Duplicatess rows")
# print(df.duplicated().sum())
# print()
# print("Remove Duplicates")
# print(df.drop_duplicates())
# print()
# print("1.using value_counts")
# print(df["Department"].value_counts())
# print()
# print("2.using value_counts")
# print(df["Age"].value_counts())
# print()
# print("2.using sort valuess")
# print(df["Marks"].sort_values(ascending=False))
# print()
# print("2.using sort valuess")
# print(df["Attendance (%)"].sort_values(ascending=False))
# print()
# print("1.Performing Group by analysis")
# print(df.groupby("Gender")["Age"].max().head(5))
# print()
# print("2.Performing Group by analysis")
# print(df.groupby("Gender")["Age"].min().head(5))
# print()
# print("3.Performing Group by analysis")
# print(df.groupby("Gender")["Attendance (%)"].mean().head(5))
# print()

# plt.hist(df["Age"],bins=5)
# plt.title("Histogram")
# plt.xlabel("value")
# plt.ylabel("Frequency")
# plt.show()

# order=df["Department"].value_counts()
# order.plot(kind="pie",autopct="%1.1f%%")
# plt.title("Pie Chart")
# plt.show()

# import matplotlib.pyplot as plt
# plt.bar(df["Department"],df["Marks"],color="red")
# plt.xlabel("X axis")
# plt.ylabel("Y axis")
# plt.title("Bar Graph")
# plt.show()


# Sports

# import pandas as pd
# import matplotlib.pyplot as plt
# df=pd.read_csv("Sport.csv")
# print(df)
# print()
# print("usinh Head")
# print(df.groupby("Team")["Matches_Played"].max().head(5))
# print()
# print("Using tail ")
# print(df.groupby("Team")["Matches_Played"].min().tail(5))
# print()
# print("Using Info")
# print(df.info())
# print()
# print("using Describe")
# print(df.describe())
# print()
# print("Handle missing values")
# print(df["Score"].fillna(df["Score"].mean()))
# print(df["Matches_Played"].fillna(df["Matches_Played"].mean()))
# print()
# print("Show Duplicates")
# print(df.duplicated())
# print()
# print("Number of Duplicatess rows")
# print(df.duplicated().sum())
# print()
# print("Remove Duplicates")
# print(df.drop_duplicates())
# print()
# print("1.using value_counts")
# print(df["Sport"].value_counts())
# print()
# print("2.using value_counts")
# print(df["Team"].value_counts())
# print()
# print("2.using sort valuess")
# print(df["Matches_Played"].sort_values(ascending=False))
# print()
# print("2.using sort valuess")
# print(df["Score"].sort_values(ascending=False))
# print()
# print("1.Performing Group by analysis")
# print(df.groupby("Gender")["Matches_Played"].max().head(5))
# print()
# print("2.Performing Group by analysis")
# print(df.groupby("Gender")["Matches_Played"].min().head(5))
# print()
# print("3.Performing Group by analysis")
# print(df.groupby("Gender")["Matches_Played"].mean().head(5))
# print()

# plt.hist(df["Age"],bins=5)
# plt.title("Histogram")
# plt.xlabel("value")
# plt.ylabel("Frequency")
# plt.show()

# order=df["Sport"].value_counts()
# order.plot(kind="pie",autopct="%1.1f%%")
# plt.title("Pie Chart")
# plt.show()

# import matplotlib.pyplot as plt
# plt.bar(df["Sport"],df["Matches_Played"],color="red")
# plt.xlabel("X axis")
# plt.ylabel("Y axis")
# plt.title("Bar Graph")
# plt.show()


# Tourism
# import pandas as pd
# import matplotlib.pyplot as plt
# df=pd.read_csv("Tourism.csv")
# print(df)
# print()
# print("using Head")
# print(df.groupby("Destination")["Travel_Cost"].max().head(5))
# print()
# print("Using tail ")
# print(df.groupby("Destination")["Travel_Cost"].min().tail(5))
# print()
# print("Using Info")
# print(df.info())
# print()
# print("using Describe")
# print(df.describe())
# print()
# print("Handle missing values")
# print(df["Trip_Duration_Days"].fillna(df["Trip_Duration_Days"].mean()))
# print(df["Travel_Cost"].fillna(df["Travel_Cost"].mean()))
# print()
# print("Show Duplicates")
# print(df.duplicated())
# print()
# print("Number of Duplicatess rows")
# print(df.duplicated().sum())
# print()
# print("Remove Duplicates")
# print(df.drop_duplicates())
# print()
# print("1.using value_counts")
# print(df["Travel_Type"].value_counts())
# print()
# print("2.using value_counts")
# a=(df["Destination"].value_counts())
# print(a)
# print()
# print("1.using sort valuess")
# print(df["Travel_Cost"].sort_values(ascending=False))
# print()
# print("2.using sort valuess")
# print(df["Trip_Duration_Days"].sort_values(ascending=False))
# print()
# print("1.Performing Group by analysis")
# print(df.groupby("Season")["Trip_Duration_Days"].max().head(5))
# print()
# print("2.Performing Group by analysis")
# print(df.groupby("Season")["Trip_Duration_Days"].min().head(5))
# print()
# print("3.Performing Group by analysis")
# print(df.groupby("Season")["Trip_Duration_Days"].mean().head(5))
# print()

# plt.hist(df["Season"],bins=5)
# plt.title("Histogram")
# plt.xlabel("value")
# plt.ylabel("Frequency")
# plt.show()

# order=df["Travel_Type"].value_counts()
# order.plot(kind="pie",autopct="%1.1f%%")
# plt.title("Pie Chart")
# plt.show()

# import matplotlib.pyplot as plt
# plt.bar(df["Age"],df["Trip_Duration_Days"],color="red")
# plt.xlabel("X axis")
# plt.ylabel("Y axis")
# plt.title("Bar Graph")
# plt.show()


# Agriculture

import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("Agricultue.csv")
print(df)
print()
print("Using Head")
print(df.head())
print()
print("Using Tail")
print(df.tail())
print()
print("Using Info")
print(df.info())
print()
print("Using Describe")
print(df.describe())
print()
print("Handle Missing Values")
print(df["Farmer_Age"].fillna(df["Farmer_Age"].mean()))
print(df["Land_Area_Acres"].fillna(df["Land_Area_Acres"].mean()))
print(df["Crop_Type"].fillna(df["Crop_Type"].mode()[0]))
print()
print("Show Duplicates")
print(df.duplicated())
print()
print("Number of Duplicate Rows")
print(df.duplicated().sum())
print()
print("Remove Duplicates")
print(df.drop_duplicates())
print()
print("1. Using value_counts")
print(df["Crop_Type"].value_counts())
print()
print("2. Using value_counts")
print(df["Season"].value_counts())
print()
print("1. Using sort_values")
print(df["Farmer_Age"].sort_values(ascending=False))
print()
print("2. Using sort_values")
print(df["Yield_Tons"].sort_values(ascending=False))
print()
print("1. Performing GroupBy Analysis")
print(df.groupby("Crop_Type")["Yield_Tons"].mean())
print()
print("2. Performing GroupBy Analysis")
print(df.groupby("Soil_Type")["Land_Area_Acres"].mean())
print()
print("3. Performing GroupBy Analysis")
print(df.groupby("Farming_Method")["Yield_Tons"].max())
print()

plt.hist(df["Yield_Tons"], bins=5, color="skyblue", edgecolor="black")
plt.title("Histogram of Yield")
plt.xlabel("Yield (Tons)")
plt.ylabel("Frequency")
plt.show()

order = df["Season"].value_counts()
order.plot(kind="pie", autopct="%1.1f%%")
plt.title("Season Distribution")
plt.ylabel("")
plt.show()


plt.bar(df["Crop_Type"], df["Yield_Tons"], color="green")
plt.xlabel("Crop Type")
plt.ylabel("Yield (Tons)")
plt.title("Crop Type vs Yield")
plt.xticks(rotation=45)
plt.show()