# import pandas as pd
# df=pd.read_csv("emp data.csv")
# print(df)
# print()
# print(df.head())
# print()
# print("Information")
# print(df.info())
# print()
# print("Filling Missing values in Experience Column")
# print(df["Experience"].fillna(df["Experience"].mean()))
# print()
# print("Filling Missing values in Salary Column")
# print(df["Salary"].fillna(df["Salary"].mean()))
# print()
# print("Filling Missing values in Performace Column")
# print(df["Performace Rating"].fillna(df["Performace Rating"].mean()))
# print()
# print("Duplicate Rows")
# print(df.duplicated())
# print()
# print("Remove Duplicate Rows")
# print(df.drop_duplicates())
# print()
# print("Department with Highest average Salary")
# print(df.groupby("Department")["Salary"].max())
# print()
# print("City With Higest Average Performace Rating")
# print(df.groupby("City")["Performace Rating"].mean().sort_values(ascending=False).head(1))
# print()
# print("Top 5 Highest Paid Employess")
# print(df.sort_values("Salary",ascending=False).head(5))
# print()


# import matplotlib.pyplot as plt
# category_salary=df.groupby("Department")["Salary"].mean()
# category_salary.plot(kind="bar")
# plt.title("Average Salary")
# plt.xlabel("x axis")
# plt.ylabel("y axis")
# plt.show()

# city=df["City"].value_counts()
# city.plot(kind="pie",autopct="%1.1f%%")
# plt.title("City Pie Chart")
# plt.show()

# plt.hist(df["Salary"],bins=5)
# plt.title("Salary Histogram")
# plt.xlabel("Value")
# plt.ylabel("Frequency")
# plt.show()


# Exercise-2
# import pandas as pd
# df=pd.read_csv("sales record.csv")
# print(df)
# print()
# df["Total"]=df["Price"]*df["Quantity"]-df["Discount"]
# print(df)
# print()
# print("higest Revenue product")
# print(df.groupby("Product")["Total"].max().head(1))
# print("lowest Revenue Product")
# print(df.groupby("Product")["Total"].min().head(1))
# print()
# print("city with Higest Order Sales")
# print(df.groupby("City")["Total"].max().head(1))
# print()
# print("Average Order Value By category")
# print(df.groupby("Category")["Quantity"].mean())
# print()

# import matplotlib.pyplot as plt
# plt.bar(df["Category"],df["Total"],color="red")
# plt.xlabel("Category")
# plt.ylabel("Revenue")
# plt.title("Category wisw revenue")
# plt.show()

# plt.hist(df["Price"])
# plt.title("Sales ditribution")
# plt.xlabel("Price")
# plt.ylabel("Frequency")
# plt.show()

# order=df["City"].value_counts()
# order.plot(kind="pie",autopct="%1.1f%%")
# plt.title("Pie Chart")
# plt.show()

# print("Business Recommendations")
# print("1. Increase the stock of best-selling products.")
# print("2. Give discounts on low-selling products.")
# print("3. Focus more on cities with high sales.")
# print("4. Advertise products that sell less.")
# print("5. Offer special deals to attract more customers.")


# exercise-3
# import pandas as pd
# df=pd.read_csv("patient record.csv")
# print(df)
# print("indentify duplicate patients")
# print(df.duplicated())
# print()
# print("Department that generating highest Revenue")
# print(df.groupby("Department")["Bill Amount"])
# print()
# print("Maximum number of patient treating by the doctor")
# doctor = df["Doctor"].value_counts()
# print(doctor.head(1))
# print()
# print(" City Contributing the Highest revenue")
# city_revenue=df.groupby("City")["Bill Amount"].sum().sort_values(ascending=False)
# print(city_revenue.head(1))
# print()

# import matplotlib.pyplot as plt

# plt.hist(df["Bill Amount"])
# plt.title("Histogram")
# plt.xlabel("value")
# plt.ylabel("Frequency")
# plt.show()

# order=df["Department"].value_counts()
# order.plot(kind="pie",autopct="%1.1f%%")
# plt.title("Pie Chart")
# plt.show()

# print(" Five Observations on hospital management")
# print("1.The department generating the highest revenue should be given more resources and staff support.")
# print("2.Doctors treating more patients may require better scheduling and workload management.")
# print("3.Cities with higher patient visits can be targeted for better healthcare services.")
# print("4.Departments with fewer patients should be promoted to increase awareness and improve services.")
# print("5.Patient records should be regularly updated to maintain accurate data and improve decision-making")


# exercise-4
import pandas as pd
df=pd.read_csv("movie record.csv")
print(df)
print()
print("Remove Duplicate Titles")
print(df[df.duplicated("Title")])
print()
print("Fill missing Rating with the average rating")
print(df["Rating"].fillna(df["Rating"].mean()))
print()
print("Most Popular Genre")
print(df["Genre"].value_counts().head(1))
print()
print("Average duration of genre")
print(df.groupby("Genre")["Duration"].mean())
print()
print("Highest rated movie")
print(df.groupby("Title")["Rating"].max().head(1))
print()
print("Number of Movies Released after 2020")
print(df[df["Release Year"]>2020])
print()

import matplotlib.pyplot as plt

# plt.hist(df["Duration"])
# plt.title("Histogram")
# plt.xlabel("value")
# plt.ylabel("Frequency")
# plt.show()

# order=df["Language"].value_counts()
# order.plot(kind="pie",autopct="%1.1f%%")
# plt.title("Pie Chart")
# plt.show()

plt.bar(df["Genre"],df["Rating"],color="red")
plt.xlabel("Genre")
plt.ylabel("Rating")
plt.title("Bar chart")
plt.show()

print("Five Insights for Streaming Platform")
print()
print("1. Popular genres should get more content investment.")
print("2. Highly rated movies can be promoted more on the platform.")
print("3. User preferences can be studied based on language distribution.")
print("4. New releases after 2020 can attract more viewers.")
print("5. Short and long duration content should be balanced for different audiences.")