Name=input("Enter your Name:"  )
Age=input("Enter your Age:")
Gender=input("Enter your gender:")
City=input("Enter City in which you live:")
Phone_no=input("Enter your Mobile no:")
print("\n***PERSONAL INFORMATIOM***\n")
print("Name:",Name)
print("Age:",Age)
print("Gender:",Gender)
print("City Name:",City)
print("Phone No.:",Phone_no)